use serde::Deserialize;

const GEMINI_ENDPOINT: &str =
    "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro:generateContent";

const SYSTEM_INSTRUCTION: &str = "\
You are a forensic linguistic auditor specialising in detecting AI-generated text in \
academic examination contexts. You will receive a student's written answer to a CA Final \
Advanced Financial Management (AFM) exam question. Analyse the text for structural, \
lexical, and syntactic markers that indicate AI authorship versus authentic student writing.\n\
\n\
AI-generated text typically exhibits: perfect grammatical structure, formulaic paragraph \
organisation, absence of personal calculation errors or self-corrections, overly even \
mark-distribution awareness, textbook-precise terminology without abbreviation, and \
consistent hedging language (e.g. 'It is important to note that...', 'This approach ensures...').\n\
\n\
Authentic student writing typically exhibits: abbreviations (NPV, IRR, MV), partial \
workings, occasional arithmetic errors or crossed-out steps, inconsistent decimal \
precision, and direct answer-first structure without narrative padding.\n\
\n\
Return a single JSON object with one field: ai_confidence (NUMBER 0.0-1.0) representing \
the probability that this answer was generated by an AI language model rather than written \
by a human student under timed examination conditions.";

#[derive(Deserialize)]
struct DetectionResult {
    ai_confidence: f64,
}

/// Analyses a free-text student answer for AI-generation markers using Gemini 2.5 Pro.
/// Returns a confidence score in [0.0, 1.0]. Values ≥ 0.80 trigger the penalty pipeline.
///
/// Temperature 0.05 keeps the forensic classification near-deterministic.
/// Texts shorter than 20 characters are trivially safe (MCQ-style "A/B/C/D") and return 0.0.
/// On any network or parse error the caller receives `Ok(0.0)` — detection failure is
/// non-fatal and must not invalidate a legitimate quiz submission.
pub async fn analyze_text_for_ai(
    client: &reqwest::Client,
    text: &str,
) -> Result<f64, String> {
    if text.trim().len() < 20 {
        return Ok(0.0);
    }

    let api_key = std::env::var("GEMINI_API_KEY")
        .map_err(|_| "GEMINI_API_KEY environment variable is not set".to_string())?;

    let url = format!("{}?key={}", GEMINI_ENDPOINT, api_key);

    let prompt = format!(
        "STUDENT ANSWER TO ANALYSE:\n\"\"\"\n{}\n\"\"\"\n\n\
         Return only a JSON object with the ai_confidence field.",
        text.trim()
    );

    let payload = serde_json::json!({
        "systemInstruction": {
            "parts": [{ "text": SYSTEM_INSTRUCTION }]
        },
        "contents": [{
            "parts": [{ "text": prompt }]
        }],
        "generationConfig": {
            "responseMimeType": "application/json",
            "responseSchema": {
                "type": "OBJECT",
                "properties": {
                    "ai_confidence": {
                        "type": "NUMBER",
                        "description": "Probability [0.0, 1.0] that this text was generated \
                                        by an AI model rather than a human student"
                    }
                },
                "required": ["ai_confidence"]
            },
            "temperature": 0.05,
            "topP": 0.80
        }
    });

    let res = client
        .post(&url)
        .json(&payload)
        .timeout(std::time::Duration::from_secs(30))
        .send()
        .await
        .map_err(|e| format!("AI detector network error: {}", e))?;

    if !res.status().is_success() {
        let status = res.status();
        let body = res.text().await.unwrap_or_default();
        return Err(format!("Gemini AI detector {} — {}", status, body));
    }

    let envelope: serde_json::Value = res
        .json()
        .await
        .map_err(|e| format!("Failed to parse AI detector response envelope: {}", e))?;

    let text_out = envelope["candidates"][0]["content"]["parts"][0]["text"]
        .as_str()
        .ok_or_else(|| {
            format!(
                "Unexpected AI detector response shape: {}",
                serde_json::to_string_pretty(&envelope).unwrap_or_default()
            )
        })?;

    let result: DetectionResult = serde_json::from_str(text_out).map_err(|e| {
        format!(
            "Failed to deserialise DetectionResult: {}. Raw: {}",
            e, text_out
        )
    })?;

    Ok(result.ai_confidence.clamp(0.0, 1.0))
}
